<?php
/**
 * Created by PhpStorm.
 * User: julien
 * Date: 13.07.18
 * Time: 14:29
 */

namespace Drupal\meetup\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;


class MeetupForm extends ConfigFormBase
{
    protected function getEditableConfigNames()
    {
        // TODO: Implement getEditableConfigNames() method.
        return [
            'meetup.adminsettings',
        ];
    }

    public function getFormId()
    {
        // TODO: Implement getFormId() method.
        return 'meetup_form';
    }

    public function buildForm(array $form, FormStateInterface $form_state)
    {
        $config = $this->config('meetup.adminsettings');

        $form['meetup_reset'] = array(
            '#type' => 'submit',
            '#value' => t('Reset'),
        );


        return parent::buildForm($form, $form_state);

    }

    public function submitForm(array &$form, FormStateInterface $form_state)
    {

        parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub

        try {
            \Drupal::database()->truncate('meetup')->execute();
            \Drupal::logger('meetup')->notice('Meetup reseted');

            drupal_set_message('Reseted');
        } catch (\Exception $e) {
            \Drupal::logger('meetup')->error($e);
        }
    }
}